# name: samuel.yoga

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           stable: 'false'
#           go-version: '1.15'
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '12'

#       - name: Build Server
#         run: | 
#           cd ./server 
#           go get . 
#           make arm 
#           make wasm
      
#       - name: Build Client
#         run: |
#           cd ./client
#           npm install
#           npm run build
#         env:
#           WS_HOST: samuel.yoga:1337

#       - name: Deploy
#         run: |
#           echo "$SSH_PRIVATE_KEY" > mykey
#           chmod 600 mykey
#           rsync -v -e 'ssh -i mykey -o StrictHostKeyChecking=no' ./server/build/server_arm32 $SSH_USER@$SSH_HOST:/home/$SSH_USER
#           rsync -vah -e 'ssh -i mykey -o StrictHostKeyChecking=no' ./client/build/ $SSH_USER@$SSH_HOST:/home/$SSH_USER/nginx/www/tanks/ --delete
#           ssh -i mykey -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST sudo service myservice restart
#         env: 
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SSH_HOST: ${{ secrets.SSH_HOST }}
#           SSH_USER: ${{ secrets.SSH_USER }}

name: Deploy

on:
  push:
    branches:
      - master
      - fix-build

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Build amd64
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: | 
          docker build -t slarsson/tanks-server-amd64 ./server
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push slarsson/tanks-server-amd64:latest
      
      - name: Build Client
        run: |
          cd ./client
          npm install
          npm run build
        env:
          WS_HOST: wss://tanks.samuel.yoga

      - name: Deploy
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey
          chmod 600 mykey
          rsync -vah -e 'ssh -i mykey -o StrictHostKeyChecking=no' ./client/build/ root@samuel.yoga:/home/html/tanks/ --delete
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart containers
        uses: appleboy/ssh-action@master
        with:
          host: samuel.yoga
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /home/asdf
            ./start.sh
