name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: build-golang
        run: cd ./server && go get . && make arm && make wasm
      - name: build-node
        run: cd ./client && npm install && npm run build