name: game.samuel.yoga

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Build amd64
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: | 
          docker build -t slarsson/tanks-server-amd64 ./server
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push slarsson/tanks-server-amd64:latest
      
      - name: Build Client
        run: |
          cd ./client
          npm install
          npm run build
        env:
          WS_HOST: wss://tanks.samuel.yoga

      - name: Deploy
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey
          chmod 600 mykey
          rsync -vah -e 'ssh -i mykey -o StrictHostKeyChecking=no' ./client/build/ root@samuel.yoga:/home/html/tanks/ --delete
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart containers
        uses: appleboy/ssh-action@master
        with:
          host: samuel.yoga
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /home/asdf
            ./start.sh
